 1. Generate a random array of size 10 by 10 and convert it into pandas dataframe with column name and row name of your interest.
 2. Perform feature scaling (minimax scaler and standard scaler) by direct calculation of minimum, maximum, mean, and standard deviation from dataframe, array.
 3. Implement Scikit-learn preprocessing pipeline to perform feature scaling.

In [3]:
import numpy as np
import pandas as pd
P = (100*np.random.rand(10, 10)).astype(int)
P

array([[33, 34, 47, 82, 31, 13, 23,  4, 31, 95],
       [42, 92, 75, 45, 34, 51, 84,  7, 18, 35],
       [72, 39, 99, 20, 49, 16, 72, 19,  6, 18],
       [51, 73, 52, 24, 44, 96, 70, 91, 70, 69],
       [82, 79, 97, 18, 87, 63, 64, 55, 74, 94],
       [99, 58, 39, 81, 73, 72, 19, 50,  1, 34],
       [31, 59, 51, 49, 64, 55, 25,  6, 52,  4],
       [ 4, 23, 58, 73, 18, 25,  6, 68,  9, 34],
       [65, 99,  2, 61, 20,  9, 29, 87, 15, 27],
       [65, 64, 12, 20, 35, 34, 73, 69, 79, 33]])

In [6]:
df = pd.DataFrame(P, columns = ['black', 'brown', 'red', 'orange', 'yellow', 'green', 'blue', 'violet', 'grey', 'white'],\
                 index = ['Bic', 'Camlin', 'Cross', 'Dunhill', 'Hero', 'Hunt', 'Pilot', 'Reynolds', 'Waterman', 'Zebra'])
df

black  brown  red  orange  yellow  green  blue  violet  grey  white
Bic          33     34   47      82      31     13    23       4    31     95
Camlin       42     92   75      45      34     51    84       7    18     35
Cross        72     39   99      20      49     16    72      19     6     18
Dunhill      51     73   52      24      44     96    70      91    70     69
Hero         82     79   97      18      87     63    64      55    74     94
Hunt         99     58   39      81      73     72    19      50     1     34
Pilot        31     59   51      49      64     55    25       6    52      4
Reynolds      4     23   58      73      18     25     6      68     9     34
Waterman     65     99    2      61      20      9    29      87    15     27
Zebra        65     64   12      20      35     34    73      69    79     33

**Feature Scaling using mini-max scaling**

In [9]:
P_mm = (P - P.min())/(P.max()-P.min())
P_mm

array([[0.32653061, 0.33673469, 0.46938776, 0.82653061, 0.30612245,
        0.12244898, 0.2244898 , 0.03061224, 0.30612245, 0.95918367],
       [0.41836735, 0.92857143, 0.75510204, 0.44897959, 0.33673469,
        0.51020408, 0.84693878, 0.06122449, 0.17346939, 0.34693878],
       [0.7244898 , 0.3877551 , 1.        , 0.19387755, 0.48979592,
        0.15306122, 0.7244898 , 0.18367347, 0.05102041, 0.17346939],
       [0.51020408, 0.73469388, 0.52040816, 0.23469388, 0.43877551,
        0.96938776, 0.70408163, 0.91836735, 0.70408163, 0.69387755],
       [0.82653061, 0.79591837, 0.97959184, 0.17346939, 0.87755102,
        0.63265306, 0.64285714, 0.55102041, 0.74489796, 0.94897959],
       [1.        , 0.58163265, 0.3877551 , 0.81632653, 0.73469388,
        0.7244898 , 0.18367347, 0.5       , 0.        , 0.33673469],
       [0.30612245, 0.59183673, 0.51020408, 0.48979592, 0.64285714,
        0.55102041, 0.24489796, 0.05102041, 0.52040816, 0.03061224],
       [0.03061224, 0.2244898 , 0.5816326

In [11]:
from sklearn import preprocessing
P_scaled = preprocessing.MinMaxScaler().fit(P).transform(P)
P_scaled

array([[0.30526316, 0.14473684, 0.46391753, 1.        , 0.1884058 ,
        0.04597701, 0.21794872, 0.        , 0.38461538, 1.        ],
       [0.4       , 0.90789474, 0.75257732, 0.421875  , 0.23188406,
        0.48275862, 1.        , 0.03448276, 0.21794872, 0.34065934],
       [0.71578947, 0.21052632, 1.        , 0.03125   , 0.44927536,
        0.08045977, 0.84615385, 0.17241379, 0.06410256, 0.15384615],
       [0.49473684, 0.65789474, 0.51546392, 0.09375   , 0.37681159,
        1.        , 0.82051282, 1.        , 0.88461538, 0.71428571],
       [0.82105263, 0.73684211, 0.97938144, 0.        , 1.        ,
        0.62068966, 0.74358974, 0.5862069 , 0.93589744, 0.98901099],
       [1.        , 0.46052632, 0.3814433 , 0.984375  , 0.79710145,
        0.72413793, 0.16666667, 0.52873563, 0.        , 0.32967033],
       [0.28421053, 0.47368421, 0.50515464, 0.484375  , 0.66666667,
        0.52873563, 0.24358974, 0.02298851, 0.65384615, 0.        ],
       [0.        , 0.        , 0.5773195

**Feature Scaling using standard scaling**

In [12]:
P_ss = (P-P.mean())/P.std()
P_ss

array([[-0.5243602 , -0.48885849, -0.02733631,  1.21522339, -0.59536361,
        -1.23439431, -0.87937725, -1.55390967, -0.59536361,  1.67674557],
       [-0.20484484,  1.57024045,  0.96671145, -0.09833973, -0.48885849,
         0.11467051,  1.2862268 , -1.44740455, -1.05688578, -0.45335678],
       [ 0.86020633, -0.31134996,  1.81875239, -0.98588237,  0.0436671 ,
        -1.1278892 ,  0.86020633, -1.02138408, -1.48290626, -1.05688578],
       [ 0.11467051,  0.89570804,  0.15017222, -0.84387555, -0.13384143,
         1.71224728,  0.78920292,  1.53473875,  0.78920292,  0.75370122],
       [ 1.21522339,  1.10871828,  1.74774898, -1.05688578,  1.39273192,
         0.54069098,  0.57619269,  0.25667733,  0.93120975,  1.64124386],
       [ 1.81875239,  0.36318245, -0.31134996,  1.17972169,  0.89570804,
         0.86020633, -1.02138408,  0.0791688 , -1.66041478, -0.48885849],
       [-0.59536361,  0.39868416,  0.11467051,  0.0436671 ,  0.57619269,
         0.25667733, -0.80837384, -1.48290626

In [13]:
P_scaled = preprocessing.StandardScaler().fit(P).transform(P)
P_scaled

array([[-0.80905204, -1.18939134, -0.20575876,  1.40633435, -0.66922681,
        -1.11403902, -0.86772599, -1.28820355, -0.15576157,  1.71967193],
       [-0.46879651,  1.27434786,  0.72347435, -0.09321525, -0.53076609,
         0.27850976,  1.38466913, -1.19530425, -0.60573944, -0.31544278],
       [ 0.66538859, -0.97700003,  1.51995986, -1.10642443,  0.16153751,
        -1.00410096,  0.94157501, -0.82370707, -1.02110362, -0.89205861],
       [-0.12854098,  0.46726088, -0.03982428, -0.94431096, -0.06923036,
         1.92758067,  0.86772599,  1.40587598,  1.19417203,  0.83778889],
       [ 1.0434503 ,  0.72213045,  1.45358607, -1.18748117,  1.91537328,
         0.718262  ,  0.64617893,  0.29108446,  1.33262676,  1.68575335],
       [ 1.68615519, -0.16991305, -0.47125393,  1.36580599,  1.26922326,
         1.04807618, -1.01542403,  0.1362523 , -1.19417203, -0.34936136],
       [-0.88466438, -0.12743479, -0.07301117,  0.06889822,  0.8538411 ,
         0.42509384, -0.79387697, -1.22627068